apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kuard-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kuard-deployment
  minReplicas: 1
  maxReplicas: 3

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 378Mi # (requests:memory + limits:memory)/2 = (256+500)/2 = 756/2 = 378
