apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    volume: postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # Данные не удаляются  автоматически
  nfs:
    server: 192.168.0.1 # IP-адрес сервера NFS
    path: "/exports/postgres" # Путь экспортируемой директории
