apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: snowflakes-replicaset
  labels:
    app: snowflakes-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snowflakes-pod
  template:
    metadata:
      labels:
        app: snowflakes-pod
    spec:
      initContainers:
        - name: worker-id-generator
          image: busybox:1.36.1
          command:
            - sh
            - -c
            - |
              WORKER_ID=$((RANDOM & 31))
              echo "WORKED_ID=$WORKER_ID" > /env/worker.env
          volumeMounts:
            - name: env-config
              mountPath: /env
      volumes:
        - name: env-config
          emptyDir: { }
      containers:
        - image: snowflakes:1.4
          name: snowflakes-container
          command: [ "sh", "-c" ]
          args:
            - . /env/worker.env;
              export WORKED_ID;
              exec java -jar app.jar
          volumeMounts:
            - name: env-config
              mountPath: /env
              readOnly: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /management/health/livenessState
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /management/health/readinessState
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
