apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: snowflakes-replicaset
  labels:
    app: snowflakes-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snowflakes-pod
  template:
    metadata:
      labels:
        app: snowflakes-pod
    spec:
      containers:
        - image: snowflakes:1.2
          name: snowflakes-container
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /management/health/livenessState
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /management/health/readinessState
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1

