replicaCount: 3
image:
  repository: jmutai/kuard-amd64
  tag: blue
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080
resources:
  requests:
    cpu: 500m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
ingress:
  enabled: true
  className: contour
  host: kuard.localdev.iprody
  tls: true
