apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-postgres-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
